### ISSUE TITLE
Imports  are not  working

### ISSUE THREAD

**Issue by yunus-ceyhan** [kvdroid/Kvdroid#21]
`from kvdroid.tools import navbar_color`

```
Traceback (most recent call last):
   File "/data/user/0/ru.iiec.pydroid3/files/temp_iiec_codefile.py", line 2, in <module>
     from kvdroid.tools import navbar_color
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kvdroid/tools/__init__.py", line 3, in <module>
     from kvdroid.jclass.android import Intent, Context
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kvdroid/jclass/android/__init__.py", line 5, in <module>
     from .app import *
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kvdroid/jclass/android/app.py", line 3, in <module>
     from kvdroid.jclass.android import VERSION
 ImportError: cannot import name 'VERSION' from partially initialized module 'kvdroid.jclass.android' (most likely due to a circular import) (/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/kvdroid/jclass/android/__init__.py)
```

@kengoon have you tested it before pull requests?

**Comment by kengoon** [comment]
@yunus-ceyhan I made a partial test, I will fix that and make a full test
