### ISSUE TITLE
[Import Error]:SystemError: NULL result without error in PyObject_Call

### ISSUE THREAD

**Issue by T-Dynamos** [kvdroid/Kvdroid#30]
I got this error 
```
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 1, in <module>
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kvdroid/__init__.py", line 5, in <module>
    from jnius import autoclass
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/jnius/__init__.py", line 42, in <module>
    from .reflect import *  # noqa
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/jnius/reflect.py", line 20, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/six.py", line 872, in __new__
    return meta(name, resolved_bases, d)
  File "jnius/jnius_export_class.pxi", line 119, in jnius.jnius.MetaJavaClass.__new__
SystemError: NULL result without error in PyObject_Call

[Program finished]

```

**Comment by kengoon** [comment]
it seems you ran your code on pydroid3 and I don't think `kvdroid` works on pydroid3. Also please always provide good description on how you got an error.

Your issue is not a kvdroid issue it is of pyjnius

**Comment by T-Dynamos** [comment]
It works when application is running but not in cli
